
name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6'
      - run: |
          cabal build
          cp `cabal exec which remotesom` remotesom-${{ github.ref_name }}
          xz -9 < remotesom-${{ github.ref_name }} > remotesom-${{ github.ref_name }}.xz
      - uses: softprops/action-gh-release@v2
        with:
          files: remotesom-${{ github.ref_name }}.xz
